steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/zero2prod:$SHORT_SHA', '.']
images: ['europe-west2-docker.pkg.dev/v4r0x-dev/zero2prod:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: 1200s
